// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento_box: dynamic(() => import("./BentoBox")),
  hero: dynamic(() => import("./Hero")),
  key_board_color_selector: dynamic(() => import("./KeyBoardColorSelector")),
};
