// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento_box: dynamic(() => import("./BentoBox")),
  hero: dynamic(() => import("./Hero")),
  key_board_color_selector: dynamic(() => import("./KeyBoardColorSelector")),
  marquee: dynamic(() => import("./Marquee")),
  purchase_button: dynamic(() => import("./PurchaseButton")),
  slice_playground: dynamic(() => import("./SwitchPlayground")),
};
